INSERT INTO NECO.USERS ("TYPE", PASSWORD, USERNAME) 
	VALUES ('admin', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684', 'admin');

INSERT INTO NECO.USERS ("TYPE", PASSWORD, USERNAME, DATEOFBIRTH, HEIGHT, "NAME", SURNAME, WEIGTH) 
	VALUES ('player', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684', 'zdenek', NULL, NULL, 'zdenek', NULL, NULL);
INSERT INTO NECO.USERS ("TYPE", PASSWORD, USERNAME, DATEOFBIRTH, HEIGHT, "NAME", SURNAME, WEIGTH) 
	VALUES ('player', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684', 'hrac2', NULL, 180, 'jan', 'dva', 80);
INSERT INTO NECO.USERS ("TYPE", PASSWORD, USERNAME, DATEOFBIRTH, HEIGHT, "NAME", SURNAME, WEIGTH) 
	VALUES ('player', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684', 'hrac3', NULL, 180, 'zdenek', 'novak', 80);
INSERT INTO NECO.USERS ("TYPE", PASSWORD, USERNAME, DATEOFBIRTH, HEIGHT, "NAME", SURNAME, WEIGTH) 
	VALUES ('player', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684', 'hrac5', NULL, 180, 'michal', 'polak', 80);
INSERT INTO NECO.USERS ("TYPE", PASSWORD, USERNAME, DATEOFBIRTH, HEIGHT, "NAME", SURNAME, WEIGTH) 
	VALUES ('player', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684', 'hrac6', NULL, 180, 'lenka', 'effenberger', 80);
INSERT INTO NECO.USERS ("TYPE", PASSWORD, USERNAME, DATEOFBIRTH, HEIGHT, "NAME", SURNAME, WEIGTH) 
	VALUES ('player', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684', 'hrac7', NULL, 180, 'jana', 'svaton', 80);
INSERT INTO NECO.USERS ("TYPE", PASSWORD, USERNAME, DATEOFBIRTH, HEIGHT, "NAME", SURNAME, WEIGTH) 
	VALUES ('player', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684', 'hrac8', NULL, 180, 'marek', 'kolman', 80);
INSERT INTO NECO.USERS ("TYPE", PASSWORD, USERNAME, DATEOFBIRTH, HEIGHT, "NAME", SURNAME, WEIGTH) 
	VALUES ('player', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684', 'hrac9', NULL, 180, 'adam', 'spicak', 80);
INSERT INTO NECO.USERS ("TYPE", PASSWORD, USERNAME, DATEOFBIRTH, HEIGHT, "NAME", SURNAME, WEIGTH) 
	VALUES ('player', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684', 'hrac10', NULL, 180, 'marian', 'obr', 80);
INSERT INTO NECO.USERS ("TYPE", PASSWORD, USERNAME, DATEOFBIRTH, HEIGHT, "NAME", SURNAME, WEIGTH) 
	VALUES ('player', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684', 'hrac11', NULL, 180, 'petr', 'bubak', 80);
INSERT INTO NECO.USERS ("TYPE", PASSWORD, USERNAME, DATEOFBIRTH, HEIGHT, "NAME", SURNAME, WEIGTH) 
	VALUES ('player', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684', 'hrac12', NULL, 180, 'david', 'hajek', 80);
INSERT INTO NECO.USERS ("TYPE", PASSWORD, USERNAME, DATEOFBIRTH, HEIGHT, "NAME", SURNAME, WEIGTH) 
	VALUES ('player', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684', 'hrac13', NULL, 180, 'jakub', 'komistr', 80);
INSERT INTO NECO.USERS ("TYPE", PASSWORD, USERNAME, DATEOFBIRTH, HEIGHT, "NAME", SURNAME, WEIGTH) 
	VALUES ('player', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684', 'hrac14', NULL, 180, 'milos', 'blatny', 80);
INSERT INTO NECO.USERS ("TYPE", PASSWORD, USERNAME, DATEOFBIRTH, HEIGHT, "NAME", SURNAME, WEIGTH) 
	VALUES ('player', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684', 'hrac15', NULL, 180, 'lukas', 'dobrovolny', 80);
INSERT INTO NECO.USERS ("TYPE", PASSWORD, USERNAME, DATEOFBIRTH, HEIGHT, "NAME", SURNAME, WEIGTH) 
	VALUES ('player', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684', 'hrac16', NULL, 180, 'jiri', 'vodrazka', 80);
INSERT INTO NECO.USERS ("TYPE", PASSWORD, USERNAME, DATEOFBIRTH, HEIGHT, "NAME", SURNAME, WEIGTH) 
	VALUES ('player', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684', 'hrac17', NULL, 180, 'tomas', 'kokoska', 80);
INSERT INTO NECO.USERS ("TYPE", PASSWORD, USERNAME, DATEOFBIRTH, HEIGHT, "NAME", SURNAME, WEIGTH) 
	VALUES ('player', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684', 'hrac18', NULL, 180, 'kamil', 'stepanek', 80);
INSERT INTO NECO.USERS ("TYPE", PASSWORD, USERNAME, DATEOFBIRTH, HEIGHT, "NAME", SURNAME, WEIGTH) 
	VALUES ('player', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684', 'hrac19', NULL, 180, 'milan', 'vesely', 80);
INSERT INTO NECO.USERS ("TYPE", PASSWORD, USERNAME, DATEOFBIRTH, HEIGHT, "NAME", SURNAME, WEIGTH) 
	VALUES ('player', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684', 'hrac20', NULL, 180, 'milos', 'mertl', 80);
INSERT INTO NECO.USERS ("TYPE", PASSWORD, USERNAME, DATEOFBIRTH, HEIGHT, "NAME", SURNAME, WEIGTH) 
	VALUES ('player', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684', 'hrac21', NULL, 180, 'nada', 'julinek', 80);
INSERT INTO NECO.USERS ("TYPE", PASSWORD, USERNAME, DATEOFBIRTH, HEIGHT, "NAME", SURNAME, WEIGTH) 
	VALUES ('player', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684', 'hrac22', NULL, 180, 'juraj', 'kapsiar', 80);
INSERT INTO NECO.USERS ("TYPE", PASSWORD, USERNAME, DATEOFBIRTH, HEIGHT, "NAME", SURNAME, WEIGTH) 
	VALUES ('player', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684', 'hrac23', NULL, 180, 'nazar', 'annagurban', 80);
INSERT INTO NECO.USERS ("TYPE", PASSWORD, USERNAME, DATEOFBIRTH, HEIGHT, "NAME", SURNAME, WEIGTH) 
	VALUES ('player', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684', 'hrac24', NULL, 180, 'nikola', 'mejsr', 80);
INSERT INTO NECO.USERS ("TYPE", PASSWORD, USERNAME, DATEOFBIRTH, HEIGHT, "NAME", SURNAME, WEIGTH) 
	VALUES ('player', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684', 'hrac25', NULL, 180, 'petr', 'muller', 80);
INSERT INTO NECO.USERS ("TYPE", PASSWORD, USERNAME, DATEOFBIRTH, HEIGHT, "NAME", SURNAME, WEIGTH) 
	VALUES ('player', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684', 'hrac26', NULL, 180, 'tereza', 'svoboda', 80);
INSERT INTO NECO.USERS ("TYPE", PASSWORD, USERNAME, DATEOFBIRTH, HEIGHT, "NAME", SURNAME, WEIGTH) 
	VALUES ('player', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684', 'hrac27', NULL, 180, 'michal', 'novotny', 80);
INSERT INTO NECO.USERS ("TYPE", PASSWORD, USERNAME, DATEOFBIRTH, HEIGHT, "NAME", SURNAME, WEIGTH) 
	VALUES ('player', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684', 'hrac28', NULL, 180, 'martin', 'cafourek', 80);
INSERT INTO NECO.USERS ("TYPE", PASSWORD, USERNAME, DATEOFBIRTH, HEIGHT, "NAME", SURNAME, WEIGTH) 
	VALUES ('player', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684', 'hrac29', NULL, 180, 'adolf', 'kvasnicka', 80);
INSERT INTO NECO.USERS ("TYPE", PASSWORD, USERNAME, DATEOFBIRTH, HEIGHT, "NAME", SURNAME, WEIGTH) 
	VALUES ('player', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684', 'hrac30', NULL, 180, 'david', 'rutrich', 80);
INSERT INTO NECO.USERS ("TYPE", PASSWORD, USERNAME, DATEOFBIRTH, HEIGHT, "NAME", SURNAME, WEIGTH) 
	VALUES ('player', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684', 'hrac31', NULL, 180, 'jindrich', 'trunecek', 80);
INSERT INTO NECO.USERS ("TYPE", PASSWORD, USERNAME, DATEOFBIRTH, HEIGHT, "NAME", SURNAME, WEIGTH) 
	VALUES ('player', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684', 'hrac32', NULL, 180, 'patrik', 'brunat', 80);
INSERT INTO NECO.USERS ("TYPE", PASSWORD, USERNAME, DATEOFBIRTH, HEIGHT, "NAME", SURNAME, WEIGTH) 
	VALUES ('player', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684', 'hrac33', NULL, 180, 'dominik', 'vcerejsek', 80);
INSERT INTO NECO.USERS ("TYPE", PASSWORD, USERNAME, DATEOFBIRTH, HEIGHT, "NAME", SURNAME, WEIGTH) 
	VALUES ('player', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684', 'hrac34', NULL, 180, 'robert', 'benda', 80);
INSERT INTO NECO.USERS ("TYPE", PASSWORD, USERNAME, DATEOFBIRTH, HEIGHT, "NAME", SURNAME, WEIGTH) 
	VALUES ('player', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684', 'hrac35', NULL, 180, 'libor', 'jenik', 80);


INSERT INTO NECO.PLACE (ADRESS, "NAME") 
	VALUES ('asd', 'asd');
INSERT INTO NECO.PLACE (ADRESS, "NAME") 
	VALUES ('Brno, Lidická 6', 'U nohy');
INSERT INTO NECO.PLACE (ADRESS, "NAME") 
	VALUES ('Na pankráci 88, Praha', 'Sokol pankrác');
INSERT INTO NECO.PLACE (ADRESS, "NAME") 
	VALUES ('Paloukova, Brno 3', 'Na palouku');
INSERT INTO NECO.PLACE (ADRESS, "NAME") 
	VALUES ('Smíchov praha 5', 'Cibulka');

INSERT INTO NECO.LEAGUE (LEAGUEEND, LEAGUESTART, "NAME") 
	VALUES (NULL, NULL, 'Vanocni bedas');
INSERT INTO NECO.LEAGUE (LEAGUEEND, LEAGUESTART, "NAME") 
	VALUES (NULL, NULL, 'vanoce 2');
INSERT INTO NECO.LEAGUE (LEAGUEEND, LEAGUESTART, "NAME") 
	VALUES (NULL, NULL, 'vanoce 3');
INSERT INTO NECO.LEAGUE (LEAGUEEND, LEAGUESTART, "NAME") 
	VALUES (NULL, NULL, 'vanoce 4');
INSERT INTO NECO.LEAGUE (LEAGUEEND, LEAGUESTART, "NAME") 
	VALUES (NULL, '2013-12-30', 'TURNAJ A');
INSERT INTO NECO.LEAGUE (LEAGUEEND, LEAGUESTART, "NAME") 
	VALUES (NULL, '2013-12-30', 'TURNAJ B');
INSERT INTO NECO.LEAGUE (LEAGUEEND, LEAGUESTART, "NAME") 
	VALUES (NULL, NULL, 'TURNAJ C');
INSERT INTO NECO.LEAGUE (LEAGUEEND, LEAGUESTART, "NAME") 
	VALUES (NULL, NULL, 'TURNAJ D');
INSERT INTO NECO.LEAGUE (LEAGUEEND, LEAGUESTART, "NAME") 
	VALUES (NULL, '2014-01-03', 'Praha Becko');



INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 3, 1);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 100, 1);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 100, 2);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 100, 3);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 100, 5);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 101, 6);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 101, 7);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 101, 8);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 101, 9);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 101, 10);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 101, 11);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 101, 12);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 101, 13);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 101, 14);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 101, 15);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 101, 16);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 101, 17);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 102, 18);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 102, 19);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 102, 20);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 102, 21);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 102, 22);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 102, 23);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 102, 24);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 102, 25);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 103, 26);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 103, 27);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 103, 28);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 103, 29);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 103, 1);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 103, 2);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 103, 3);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 102, 2);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 5, 2);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 5, 3);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 6, 3);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 2, 2);
INSERT INTO NECO.ENROLL (PAID, LEAGUE_ID, PLAYER_ID) 
	VALUES (NULL, 3, 2);



INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (102);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (102);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (102);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (102);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (102);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (102);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (102);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (102);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (102);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (102);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (102);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (102);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (102);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (102);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (102);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (102);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (102);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (102);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (102);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (102);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (102);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (102);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (102);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (102);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (102);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (102);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (102);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (102);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (101);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (100);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (100);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (100);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (100);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (100);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (100);
INSERT INTO NECO.MATCHES (LEAGUE_ID) 
	VALUES (5);



INSERT INTO NECO.MATCH_SETS ("NUMBER", SCORE, NOTE_ID) 
	VALUES (1, 15, 201);
INSERT INTO NECO.MATCH_SETS ("NUMBER", SCORE, NOTE_ID) 
	VALUES (1, 21, 202);
INSERT INTO NECO.MATCH_SETS ("NUMBER", SCORE, NOTE_ID) 
	VALUES (2, 14, 201);
INSERT INTO NECO.MATCH_SETS ("NUMBER", SCORE, NOTE_ID) 
	VALUES (2, 21, 202);
INSERT INTO NECO.MATCH_SETS ("NUMBER", SCORE, NOTE_ID) 
	VALUES (1, 21, 197);
INSERT INTO NECO.MATCH_SETS ("NUMBER", SCORE, NOTE_ID) 
	VALUES (1, 15, 198);
INSERT INTO NECO.MATCH_SETS ("NUMBER", SCORE, NOTE_ID) 
	VALUES (2, 5, 197);
INSERT INTO NECO.MATCH_SETS ("NUMBER", SCORE, NOTE_ID) 
	VALUES (2, 21, 198);
INSERT INTO NECO.MATCH_SETS ("NUMBER", SCORE, NOTE_ID) 
	VALUES (3, 21, 197);
INSERT INTO NECO.MATCH_SETS ("NUMBER", SCORE, NOTE_ID) 
	VALUES (3, 2, 198);
INSERT INTO NECO.MATCH_SETS ("NUMBER", SCORE, NOTE_ID) 
	VALUES (3, 21, 201);
INSERT INTO NECO.MATCH_SETS ("NUMBER", SCORE, NOTE_ID) 
	VALUES (3, 2, 202);
INSERT INTO NECO.MATCH_SETS ("NUMBER", SCORE, NOTE_ID) 
	VALUES (4, 5, 197);
INSERT INTO NECO.MATCH_SETS ("NUMBER", SCORE, NOTE_ID) 
	VALUES (4, 21, 198);
INSERT INTO NECO.MATCH_SETS ("NUMBER", SCORE, NOTE_ID) 
	VALUES (4, 0, 201);
INSERT INTO NECO.MATCH_SETS ("NUMBER", SCORE, NOTE_ID) 
	VALUES (4, 21, 202);


INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 1, 18);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 1, 19);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 2, 18);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 2, 20);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 3, 18);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 3, 21);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 4, 18);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 4, 22);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 5, 18);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 5, 23);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 6, 18);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 6, 24);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 7, 18);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 7, 25);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 8, 19);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 8, 20);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 9, 19);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 9, 21);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 10, 19);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 10, 22);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 11, 19);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 11, 23);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 12, 19);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 12, 24);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 13, 19);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 13, 25);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 14, 20);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 14, 21);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 15, 20);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 15, 22);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 16, 20);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 16, 23);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 17, 20);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 17, 24);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 18, 20);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 18, 25);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 19, 21);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 19, 22);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 20, 21);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 20, 23);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 21, 21);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 21, 24);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 22, 21);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 22, 25);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 23, 22);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 23, 23);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 24, 22);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 24, 24);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 25, 22);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 25, 25);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 26, 23);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 26, 24);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 27, 23);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 27, 25);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 28, 24);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 28, 25);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 29, 6);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 29, 7);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 30, 6);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 30, 8);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 31, 6);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 31, 9);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 32, 6);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 32, 10);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 33, 6);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 33, 11);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 34, 6);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 34, 12);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 35, 6);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 35, 13);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 36, 6);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 36, 14);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 37, 6);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 37, 15);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 38, 6);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 38, 16);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 39, 6);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 39, 17);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 40, 7);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 40, 8);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 41, 7);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 41, 9);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 42, 7);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 42, 10);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 43, 7);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 43, 11);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 44, 7);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 44, 12);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 45, 7);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 45, 13);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 46, 7);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 46, 14);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 47, 7);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 47, 15);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 48, 7);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 48, 16);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 49, 7);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 49, 17);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 50, 8);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 50, 9);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 51, 8);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 51, 10);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 52, 8);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 52, 11);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 53, 8);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 53, 12);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 54, 8);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 54, 13);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 55, 8);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 55, 14);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 56, 8);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 56, 15);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 57, 8);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 57, 16);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 58, 8);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 58, 17);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 59, 9);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 59, 10);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 60, 9);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 60, 11);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 61, 9);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 61, 12);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 62, 9);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 62, 13);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 63, 9);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 63, 14);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 64, 9);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 64, 15);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 65, 9);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 65, 16);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 66, 9);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 66, 17);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 67, 10);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 67, 11);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 68, 10);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 68, 12);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 69, 10);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 69, 13);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 70, 10);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 70, 14);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 71, 10);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 71, 15);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 72, 10);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 72, 16);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 73, 10);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 73, 17);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 74, 11);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 74, 12);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 75, 11);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 75, 13);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 76, 11);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 76, 14);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 77, 11);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 77, 15);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 78, 11);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 78, 16);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 79, 11);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 79, 17);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 80, 12);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 80, 13);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 81, 12);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 81, 14);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 82, 12);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 82, 15);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 83, 12);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 83, 16);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 84, 12);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 84, 17);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 85, 13);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 85, 14);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 86, 13);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 86, 15);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 87, 13);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 87, 16);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 88, 13);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 88, 17);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 89, 14);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 89, 15);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 90, 14);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 90, 16);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 91, 14);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 91, 17);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 92, 15);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 92, 16);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 93, 15);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 93, 17);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 94, 16);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 94, 17);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 95, 1);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 95, 2);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 96, 1);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 96, 3);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 97, 1);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 97, 5);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 98, 2);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 98, 3);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 99, 2);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 99, 5);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 100, 3);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 100, 5);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (1, 0, 101, 2);
INSERT INTO NECO.NOTE ("NUMBER", SCORE, MATCH_ID, PLAYER_ID) 
	VALUES (2, 0, 101, 3);

INSERT INTO NECO.PROPOSAL (MATCHAGREED, MATCHPLAYED, PROPDATE, MATCH_ID, PLACE_ID, PLAYER_ID) 
	VALUES (0, 0, '2014-01-20', 101, 2, 2);
INSERT INTO NECO.PROPOSAL (MATCHAGREED, MATCHPLAYED, PROPDATE, MATCH_ID, PLACE_ID, PLAYER_ID) 
	VALUES (0, 0, '2014-01-21', 101, 200, 2);
INSERT INTO NECO.PROPOSAL (MATCHAGREED, MATCHPLAYED, PROPDATE, MATCH_ID, PLACE_ID, PLAYER_ID) 
	VALUES (1, 0, '2014-01-15', 101, 200, 2);
INSERT INTO NECO.PROPOSAL (MATCHAGREED, MATCHPLAYED, PROPDATE, MATCH_ID, PLACE_ID, PLAYER_ID) 
	VALUES (0, 0, '2014-01-07', 101, 1, 3);
INSERT INTO NECO.PROPOSAL (MATCHAGREED, MATCHPLAYED, PROPDATE, MATCH_ID, PLACE_ID, PLAYER_ID) 
	VALUES (0, 0, '2014-01-15', 101, 1, 2);
INSERT INTO NECO.PROPOSAL (MATCHAGREED, MATCHPLAYED, PROPDATE, MATCH_ID, PLACE_ID, PLAYER_ID) 
	VALUES (0, 0, '2014-01-15', 101, 1, 2);
INSERT INTO NECO.PROPOSAL (MATCHAGREED, MATCHPLAYED, PROPDATE, MATCH_ID, PLACE_ID, PLAYER_ID) 
	VALUES (0, 0, '2014-01-06', 101, 1, 2);
INSERT INTO NECO.PROPOSAL (MATCHAGREED, MATCHPLAYED, PROPDATE, MATCH_ID, PLACE_ID, PLAYER_ID) 
	VALUES (0, 0, '1970-01-07', 101, 1, 2);
INSERT INTO NECO.PROPOSAL (MATCHAGREED, MATCHPLAYED, PROPDATE, MATCH_ID, PLACE_ID, PLAYER_ID) 
	VALUES (0, 0, '1970-01-14', 101, 1, 2);
INSERT INTO NECO.PROPOSAL (MATCHAGREED, MATCHPLAYED, PROPDATE, MATCH_ID, PLACE_ID, PLAYER_ID) 
	VALUES (1, 0, '1970-08-13', 99, 200, 5);
INSERT INTO NECO.PROPOSAL (MATCHAGREED, MATCHPLAYED, PROPDATE, MATCH_ID, PLACE_ID, PLAYER_ID) 
	VALUES (0, 0, '1970-08-12', 99, 200, 5);
INSERT INTO NECO.PROPOSAL (MATCHAGREED, MATCHPLAYED, PROPDATE, MATCH_ID, PLACE_ID, PLAYER_ID) 
	VALUES (0, 0, '1970-08-05', 99, 200, 5);

